print("이름을 입력하세요: ",end="")
name = input("")
print("학번을 입력하세요: ",end="")
student_number = input("")
print("학과를 입력하세요: ",end="")
department = input("")
print("학교를 입력하세요: ",end="")
school_name = input("")
print("")
print("<출력>")
print("이름: "+name)
print("학번: "+student_number)
print("학과: "+department)
print("학교: "+school_name)
